# This workflow will build a Java project with Maven
name: Notebook app on java 17

on:
    push:
        branches:
          - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: 17
          - name: Cache Maven packages
            uses: actions/cache@v3
            with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                restore-keys: ${{ runner.os }}-m2-
          - name: Build with Maven
            run: >
                mvn -f com.examples.notebook/pom.xml
                clean verify -Pjacoco