# This workflow will build a Java project with Maven
name: Notebook app on java 17

on:
    push:
        branches:
          - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            workdir: com.examples.notebook

        steps:
          - uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: 17
          - name: Cache Maven packages
            uses: actions/cache@v3
            with:
                path: |
                    ~/.m2
                    ~/.sonar/cache
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                restore-keys: ${{ runner.os }}-m2-
          - name: Build with Maven
            run: >
                xvfb-run mvn verify
                -Pcoveralls
                -DrepoToken=$COVERALLS_REPO_TOKEN
                -DpullRequest=${{ github.event.pull_request.number }}
            working-directory: ${{ env.workdir }}
            env:
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          - name: Generate JUnit Reports
            run: >
                mvn surefire-report:report-only surefire-report:failsafe-report-only site:site -DgenerateReports=false
            working-directory: ${{ env.workdir }}
            if: ${{ failure() }}
          - name: Archive JUnit Report
            uses: actions/upload-artifact@v3
            if: ${{ failure() }}
            with:
                name: Reports
                path: '**/target/site'
          - name: Run Mutation Testing
            id: mutation
            run: mvn org.pitest:pitest-maven:mutationCoverage
            if: github.event_name == 'pull_request'
            working-directory: ${{ env.workdir }}
          - name: Archive Mutation Testing
            uses: actions/upload-artifact@v3
            if: steps.mutation.outcome == 'failure'
            with:
                name: mutation-testing
                path: '**/target/pit-reports'
          - name: Verify code quality
            run: >
                mvn sonar:sonar
                -Dsonar.organization=jacopos97
                -Dsonar.projectKey=jacopos97_notebook-project
                -Dsonar.host.url=https://sonarcloud.io
            working-directory: ${{ env.workdir }}
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}